import { flow, Instance, SnapshotOut, types } from "mobx-state-tree";
import { omit } from "ramda";
import { Api } from "../../services/api";
import { showAlert } from "../../utils/utils";
// const parseString = require('react-native-xml2js').parseString
const parseString = require("react-native-xml2js").parseString;

/**
 * Model description here for TypeScript hints.
 */
const api = new Api();
api.setup();
/**
 * Model description here for TypeScript hints.
 */
export const LookupModel = types
  .model("LookupStore")
  .props({
     
    IsCommodityLoading:false,
    IsRelatedObjectLoading:false,
    isEmptyCommodityList:false,
    IsPaymentMethodLoading:false,
    isEmptySearchCommodityList:false,
    CurrencyLookup: types.optional(types.frozen(), [
      //name key is must.It is to show the text in front
      { id: 1 ,  name:"AED"},
      { id: 2 ,  name:"ZAR"},
      { id: 3 ,  name:"AST"},
      { id: 4 ,  name:"AUD"},
      { id: 5 ,  name:"BEF"},
      { id: 6 ,  name:"BHD"},
      { id: 7 ,  name:"CAD"},
      { id: 8 ,  name:"CHF"},
      { id: 9 ,  name:"CNY"},
      { id: 10 ,  name:"USD"},
      { id: 11 ,  name:"DKK"},
      { id: 12 ,  name:"EGP"},
      { id: 13 ,  name:"ETB"},
      { id: 14 ,  name:"EUR"},
      { id: 15 ,  name:"FIM"},
      { id: 16 ,  name:"GBP"},
      { id: 17 ,  name:"GRD"},
      { id: 18 ,  name:"HKD"},
      { id: 19 ,  name:"INR"},
      { id: 20 ,  name:"IRR"},
      { id: 21 ,  name:"JOD"},
      { id: 22 ,  name:"JPY"},
      { id: 23 ,  name:"KES"},
      { id: 24 ,  name:"KWD"},
      { id: 25 ,  name:"LBP"},
      { id: 26 ,  name:"LYD"},
      { id: 27 ,  name:"SGD"},
      { id: 28 ,  name:"MYR"},
      { id: 29 ,  name:"NGN"},
      { id: 30 ,  name:"NLG"},
      { id: 31 ,  name:"NOK"},
      { id: 32 ,  name:"OMR"},
      { id: 33 ,  name:"PKR"},
      { id: 34 ,  name:"QAR"},
      { id: 35 ,  name:"RSP"},
      { id: 36 ,  name:"SAR"},
      { id: 37 ,  name:"SDG"},
      { id: 38 ,  name:"SEK"},
      { id: 39 ,  name:"SYP"},
      { id: 40 ,  name:"DEM"},
      { id: 42 ,  name:"TRY"},
      { id: 43 ,  name:"THB"},
    ]),
    PaymentMethodLookup: types.optional(types.frozen(), [
      //name key is must.It is to show the text in front
{ id: 1 ,  name:"اعتماد مستندي اطلاع"},
{ id: 2 ,  name:"اعتماد مستندي قبول"},
{ id: 3 ,  name:"الدفع المقدم"},
{ id: 4 ,  name:"الدفع ضد المستندات"},
{ id: 5 ,  name:"التحصيل المستندي قبول"},
{ id: 6 ,  name:"البيع تحت التصريف"},
{ id: 7 ,  name:"دفع اجل"},
{ id: 8 ,  name:"قرض"},
{ id: 9 ,  name:"اعتماد مستندي مؤجل الدفع"},
{ id: 10 ,  name:"بدون قيمة"},
{ id: 14 ,  name:"مستندات مقابل القبول"},
    ]),
    
    PurposeLookup: types.optional(types.frozen(), [
      {label: "اعادة صادر للصيانة", value: "1"},
      {label: "اعادة صادر للإستبدال",value: "2"},
      {label: "هدايا أو عينات بقيمة", value: "3"},
      {label: "هدايا أو عينات بدون قيمة", value: "4"},
      {label: "اعادة صادر نهائي", value: "5"},
      {label: "بترول خام", value: "6"},
      {label: "خام النيل",value: "7"},
      {label: "خام دار  ", value: "8"},
      {label: "التصنيع و الإعادة" , value: "9"},
      {label: "التعبئة و الإعادة", value: "10" },
    ]),



    
    ImportPurposeLookup: types.optional(types.frozen(), [
      //name key is must.It is to show the text in front
{ id: 1 ,  name:"تجاري"},
{ id: 2 ,  name:"شخصي"},
{ id: 3 ,  name:"إستثمار"},
{ id: 4 ,  name:"حكومي"},
{ id: 5 ,  name:"صناعي"},
    ]),

    ShippingTypeLookup: types.optional(types.frozen(), [
      //name key is must.It is to show the text in front
      { label: "كلي", value: "1" },
      { label: "جزئي", value: "2" },
    ]),
    CountryLookup: types.optional(types.frozen(), [
      //name key is must.It is to show the text in front
      { id: 1 ,  name:"أروبا"},
      { id: 2 ,  name:"أفغانستان"},
      { id: 3 ,  name:"أنغولا"},
      { id: 4 ,  name:"أنغيلا"},
      { id: 5 ,  name:"جزر الأرض"},
      { id: 6 ,  name:"ألبانيا"},
      { id: 7 ,  name:"أندورا"},
      { id: 8 ,  name:"جزر الأنتيل الهولندية"},
      { id: 9 ,  name:"الامارات العربية المتحدة"},
      { id: 10 ,  name:"الأرجنتين"},
      { id: 11 ,  name:"أرمينيا"},
      { id: 12 ,  name:"ساموا الأمريكية"},
      { id: 13 ,  name:"القارة القطبية الجنوبية"},
      { id: 14 ,  name:"الأراضي الفرنسية الجنوبية والقطب الجنوبي"},
      { id: 15 ,  name:"انتيغوا وبربودا"},
      { id: 16 ,  name:"أستراليا"},
      { id: 17 ,  name:"النمسا"},
      { id: 18 ,  name:"أذربيجان"},
      { id: 19 ,  name:"بورندي"},
      { id: 20 ,  name:"بلجيكا"},
      { id: 21 ,  name:"بنين"},
      { id: 22 ,  name:"بونير، سينت اوستاتيوس وسابا"},
      { id: 23 ,  name:"بوركينا فاسو"},
      { id: 24 ,  name:"بنجلاديش"},
      { id: 25 ,  name:"بلغاريا"},
      { id: 26 ,  name:"البحرين"},
      { id: 27 ,  name:"جزر البهاما"},
      { id: 28 ,  name:"البوسنة والهرسك"},
      { id: 29 ,  name:"سانت بارتيليمي"},
      { id: 30 ,  name:"روسيا البيضاء"},
      { id: 31 ,  name:"بليز"},
      { id: 32 ,  name:"برمودا"},
      { id: 33 ,  name:"بوليفيا، الدولة المتعددة القوميات"},
      { id: 34 ,  name:"البرازيل"},
      { id: 35 ,  name:"بربادوس"},
      { id: 36 ,  name:"بروناي دار السلام"},
      { id: 37 ,  name:"بوتان"},
      { id: 38 ,  name:"جزيرة بوفيه"},
      { id: 39 ,  name:"بوتسوانا"},
      { id: 40 ,  name:"جمهورية افريقيا الوسطى"},
      { id: 41 ,  name:"كندا"},
      { id: 42 ,  name:"كوكوس (كيلينغ)"},
      { id: 43 ,  name:"سويسرا"},
      { id: 44 ,  name:"تشيلي"},
      { id: 45 ,  name:"الصين"},
      { id: 46 ,  name:"ساحل العاج"},
      { id: 47 ,  name:"الكاميرون"},
      { id: 48 ,  name:"جمهورية الكونغو الديمقراطية من"},
      { id: 49 ,  name:"جمهورية الكونغو"},
      { id: 50 ,  name:"جزر كوك"},
      { id: 51 ,  name:"كولومبيا"},
      { id: 52 ,  name:"جزر القمر"},
      { id: 53 ,  name:"الرأس الأخضر"},
      { id: 54 ,  name:"كوستاريكا"},
      { id: 55 ,  name:"كوبا"},
      { id: 56 ,  name:"كوراساو"},
      { id: 57 ,  name:"عيد الميلاد جزر"},
      { id: 58 ,  name:"جزر كايمان"},
      { id: 59 ,  name:"قبرص"},
      { id: 60 ,  name:"جمهورية التشيك"},
      { id: 61 ,  name:"ألمانيا"},
      { id: 62 ,  name:"جيبوتي"},
      { id: 63 ,  name:"دومينيكا"},
      { id: 64 ,  name:"الدنمارك"},
      { id: 65 ,  name:"جمهورية الدومينيكان"},
      { id: 66 ,  name:"الجزائر"},
      { id: 67 ,  name:"الاكوادور"},
      { id: 68 ,  name:"مصر"},
      { id: 69 ,  name:"اريتريا"},
      { id: 70 ,  name:"يسترن الصحراء"},
      { id: 71 ,  name:"إسبانيا"},
      { id: 72 ,  name:"استونيا"},
      { id: 73 ,  name:"أثيوبيا"},
      { id: 74 ,  name:"فنلندا"},
      { id: 75 ,  name:"فيجي"},
      { id: 76 ,  name:"جزر فوكلاند (مالفيناس)"},
      { id: 77 ,  name:"فرنسا"},
      { id: 78 ,  name:"جزر فارو"},
      { id: 79 ,  name:"ميكرونيزيا، دولة اتحادية من"},
      { id: 80 ,  name:"فرنسا، متروبوليتان"},
      { id: 81 ,  name:"الجابون"},
      { id: 82 ,  name:"المملكة المتحدة"},
      { id: 83 ,  name:"جورجيا"},
      { id: 84 ,  name:"غيرنسي"},
      { id: 85 ,  name:"غانا"},
      { id: 86 ,  name:"جبل طارق"},
      { id: 87 ,  name:"غينيا"},
      { id: 88 ,  name:"جوادلوب"},
      { id: 89 ,  name:"غامبيا"},
      { id: 90 ,  name:"غينيا بيساو"},
      { id: 91 ,  name:"غينيا الاستوائية"},
      { id: 92 ,  name:"يونان"},
      { id: 93 ,  name:"غرينادا"},
      { id: 94 ,  name:"غرينلاند"},
      { id: 95 ,  name:"غواتيمالا"},
      { id: 96 ,  name:"الفرنسية، جيانا"},
      { id: 97 ,  name:"غوام"},
      { id: 98 ,  name:"غيانا"},
      { id: 99 ,  name:"هونج كونج"},
      { id: 100 ,  name:"جزيرة هيرد وماكدونالد"},
      { id: 101 ,  name:"هندوراس"},
      { id: 102 ,  name:"كرواتيا"},
      { id: 103 ,  name:"هايتي"},
      { id: 104 ,  name:"هنغاريا"},
      { id: 105 ,  name:"أندونيسيا"},
      { id: 106 ,  name:"جزيرة مان"},
      { id: 107 ,  name:"الهند"},
      { id: 108 ,  name:"إقليم المحيط الهندي البريطاني"},
      { id: 109 ,  name:"أيرلندا"},
      { id: 110 ,  name:"إيران، الجمهورية الإسلامية"},
      { id: 111 ,  name:"العراق"},
      { id: 112 ,  name:"أيسلندا"},
      { id: 113 ,  name:"إيطاليا"},
      { id: 114 ,  name:"جامايكا"},
      { id: 115 ,  name:"جيرسي"},
      { id: 116 ,  name:"الأردن"},
      { id: 117 ,  name:"اليابان"},
      { id: 118 ,  name:"كازاخستان"},
      { id: 119 ,  name:"كينيا"},
      { id: 120 ,  name:"قرغيزستان"},
      { id: 121 ,  name:"كمبوديا"},
      { id: 122 ,  name:"كيريباتي"},
      { id: 123 ,  name:"سانت كيتس ونيفيس"},
      { id: 124 ,  name:"كوريا الجنوبية"},
      { id: 125 ,  name:"الكويت"},
      { id: 126 ,  name:"لاوس"},
      { id: 127 ,  name:"لبنان"},
      { id: 128 ,  name:"Lipiria"},
      { id: 129 ,  name:"ليبيا"},
      { id: 130 ,  name:"سانت لوسيا"},
      { id: 131 ,  name:"ليختنشتاين"},
      { id: 132 ,  name:"سري لانكا"},
      { id: 133 ,  name:"ليسوتو"},
      { id: 134 ,  name:"ليتوانيا"},
      { id: 135 ,  name:"لوكسنبورج"},
      { id: 136 ,  name:"لاتفيا"},
      { id: 137 ,  name:"ماكاو"},
      { id: 138 ,  name:"سانت مارتن (الجزء الفرنسية)"},
      { id: 139 ,  name:"المملكة المغربية"},
      { id: 140 ,  name:"موناكو"},
      { id: 141 ,  name:"مولدافيا"},
      { id: 142 ,  name:"مدغشقر"},
      { id: 143 ,  name:"جزر المالديف"},
      { id: 144 ,  name:"المكسيك"},
      { id: 145 ,  name:"جزر مارشال"},
      { id: 146 ,  name:"مقدونيا، جمهورية"},
      { id: 147 ,  name:"مالي"},
      { id: 148 ,  name:"مالطا"},
      { id: 149 ,  name:"بورما"},
      { id: 150 ,  name:"الجبل الأسود"},
      { id: 151 ,  name:"منغوليا"},
      { id: 152 ,  name:"ماريانا الشمالية جزيرة"},
      { id: 153 ,  name:"موزمبيق"},
      { id: 154 ,  name:"موريتانيا"},
      { id: 155 ,  name:"مونتسيرات"},
      { id: 156 ,  name:"Martiniqe"},
      { id: 157 ,  name:"موريشيوس"},
      { id: 158 ,  name:"ملاوي"},
      { id: 159 ,  name:"ماليزيا"},
      { id: 160 ,  name:"مايوت"},
      { id: 161 ,  name:"ناميبيا"},
      { id: 162 ,  name:"كاليدونيا الجديدة"},
      { id: 163 ,  name:"النيجر"},
      { id: 164 ,  name:"جزيرة نورفولك"},
      { id: 165 ,  name:"نيجيريا"},
      { id: 166 ,  name:"نيكاراغوا"},
      { id: 167 ,  name:"نيوي"},
      { id: 168 ,  name:"هولندا"},
      { id: 169 ,  name:"النرويج"},
      { id: 170 ,  name:"نيبال"},
      { id: 171 ,  name:"ناورو"},
      { id: 172 ,  name:"نيوزيلندا"},
      { id: 173 ,  name:"عمان"},
      { id: 174 ,  name:"باكستان"},
      { id: 175 ,  name:"بنما"},
      { id: 176 ,  name:"جزر بيتكيرن"},
      { id: 177 ,  name:"بيرو"},
      { id: 178 ,  name:"الفلبين"},
      { id: 179 ,  name:"بالاو"},
      { id: 180 ,  name:"بابوا غينيا الجديدة"},
      { id: 181 ,  name:"بولندا"},
      { id: 182 ,  name:"بورتوريكو"},
      { id: 183 ,  name:"كوريا، شمال"},
      { id: 184 ,  name:"البرتغال"},
      { id: 185 ,  name:"باراغواي"},
      { id: 186 ,  name:"الفرنسية، بولينيزيا"},
      { id: 187 ,  name:"قطر"},
      { id: 188 ,  name:"جمع شمل"},
      { id: 189 ,  name:"رومانيا"},
      { id: 190 ,  name:"رومانيا"},
      { id: 191 ,  name:"روسيا"},
      { id: 192 ,  name:"رواندا"},
      { id: 193 ,  name:"السعودية"},
      { id: 194 ,  name:"السودان وجمهورية الكونغو الديمقراطية"},
      { id: 195 ,  name:"السودان"},
      { id: 196 ,  name:"السنغال"},
      { id: 197 ,  name:"سنغافورة"},
      { id: 198 ,  name:"جورجيا الجنوبية وجزر جنوب"},
      { id: 199 ,  name:"سانت هيلانة"},
      { id: 200 ,  name:"سفالبارد وجان مايان"},
      { id: 201 ,  name:"جزر سليمان"},
      { id: 202 ,  name:"سيراليون"},
      { id: 203 ,  name:"السلفادور"},
      { id: 204 ,  name:"سان مارينو"},
      { id: 205 ,  name:"الصومال"},
      { id: 206 ,  name:"سان بيار وميكلون"},
      { id: 207 ,  name:"صربيا"},
      { id: 208 ,  name:"جنوب السودان"},
      { id: 209 ,  name:"السودان سوث الحكومة"},
      { id: 210 ,  name:"ساو تومي وبرينسيبي"},
      { id: 211 ,  name:"سورينام"},
      { id: 212 ,  name:"سلوفاكيا"},
      { id: 213 ,  name:"سلوفينيا"},
      { id: 214 ,  name:"السويد"},
      { id: 215 ,  name:"سوازيلاند"},
      { id: 216 ,  name:"سانت مارتن (الهولندية جزءا منها)"},
      { id: 217 ,  name:"سيشل"},
      { id: 218 ,  name:"الجمهورية العربية السورية"},
      { id: 219 ,  name:"جزر تركس وكايكوس"},
      { id: 220 ,  name:"تشاد"},
      { id: 221 ,  name:"توغو"},
      { id: 222 ,  name:"تايلاند"},
      { id: 223 ,  name:"طاجيكستان"},
      { id: 224 ,  name:"توكيلاو"},
      { id: 225 ,  name:"تركمانستان"},
      { id: 226 ,  name:"تيمور الشرقية"},
      { id: 227 ,  name:"تيمور الشرقية"},
      { id: 228 ,  name:"تونغا"},
      { id: 229 ,  name:"ترينيداد وتوباغو"},
      { id: 230 ,  name:"تونس"},
      { id: 231 ,  name:"تركيا"},
      { id: 232 ,  name:"توفالو"},
      { id: 233 ,  name:"مقاطعة تايوان الصينية"},
      { id: 234 ,  name:"تنزانيا المتحدة، جمهورية"},
      { id: 235 ,  name:"اوغندا"},
      { id: 236 ,  name:"أوكرانيا"},
      { id: 237 ,  name:"الولايات المتحدة البعيدة الصغيرة جزيرة"},
      { id: 238 ,  name:"أوروغواي"},
      { id: 239 ,  name:"الولايات المتحدة"},
      { id: 240 ,  name:"أوزبكستان"},
      { id: 241 ,  name:"الكرسي الرسولي (الفاتيكان)"},
      { id: 242 ,  name:"سانت فنسنت وغرينادين"},
      { id: 243 ,  name:"فنزويلا، الجمهورية البوليفارية"},
      { id: 244 ,  name:"الجزر العذراء البريطانية"},
      { id: 245 ,  name:"الجزر العذراء، الولايات المتحدة"},
      { id: 246 ,  name:"فيتنام"},
      { id: 247 ,  name:"فانواتو"},
      { id: 248 ,  name:"واليس وفوتونا"},
      { id: 249 ,  name:"ساموا"},
      { id: 250 ,  name:"اليمن"},
      { id: 251 ,  name:"يوغوسلافيا"},
      { id: 252 ,  name:"جنوب أفريقيا"},
      { id: 253 ,  name:"جمهورية الكونغو الديمقراطية"},
      { id: 254 ,  name:"زامبيا"},
      { id: 255 ,  name:"زيمبابوي"},
      { id: 256 ,  name:"تايلاند"},
      { id: 257 ,  name:"تايوان"},
      { id: 258 ,  name:"الأراضي الفلسطينية"},
      { id: 259 ,  name:"الأراضي الفلسطينية"},
      { id: 261 ,  name:"بيلاروسيا"},
    ]),
    LoadingPortLookup: types.optional(types.frozen(), [
      //name key is must.It is to show the text in front
      { id: 1 ,  name:"أدارة جمارك مطار الخرطوم"},
{ id: 2 ,  name:"أدارة جمارك الحاويات سوبا "},
{ id: 3 ,  name:"ادارة جمارك المنطقة الحرة  قري"},
{ id: 4 ,  name:"جمارك المستودعات ام درمان"},
{ id: 5 ,  name:"مكافحة التهريب الخرطوم"},
{ id: 6 ,  name:"جمارك الميناء الشمالي – بور تسودان"},
{ id: 7 ,  name:"جمارك الميناءالجنوبي  – بور تسودان"},
{ id: 8 ,  name:"(محطة ميناء عثمان دقنة (سواكن"},
{ id: 9 ,  name:"المنطقة الحرة بور تسودان"},
{ id: 10 ,  name:"جمارك اوسيف"},
{ id: 11 ,  name:"جمارك وادي حلفا"},
{ id: 12 ,  name:"فرع جمارك كريمة "},
{ id: 13 ,  name:"فرع جمارك ابوحمد"},
{ id: 14 ,  name:"فرع جمارك العبيدية"},
{ id: 15 ,  name:"فرع جمارك الميناء الجاف عطبرة"},
{ id: 16 ,  name:"فرع جمارك الميناء الجاف ودمدني   "},
{ id: 17 ,  name:"فرع جمارك القضارف "},
{ id: 18 ,  name:"جمارك الميناء الجاف كوستي"},
{ id: 19 ,  name:"الجمارك فرع دنقلا"},
{ id: 20 ,  name:"محطة القلابات"},
{ id: 21 ,  name:"محطة النقل النهري كوستي"},
{ id: 22 ,  name:"محطة الابيض"},
{ id: 23 ,  name:"الجمارك محطة نيالا"},
{ id: 24 ,  name:"الجمارك محطة الجنينة"},
{ id: 25 ,  name:"الجمارك محطة الفاشر"},
{ id: 26 ,  name:"الجمارك محطة ام دافوق"},
{ id: 27 ,  name:"الجمارك محطة كسلا"},
{ id: 28 ,  name:"محطة الدمازين الجمركية"},
{ id: 29 ,  name:"فرع جمارك المصفاة"},
{ id: 30 ,  name:"محطة اشكيت"},
    ]),

  BankDropDownList: types.optional(types.frozen(), [
      //label key is must.It is to show the text in front
{ value: 1 ,  label:"بنك السودان المركزى"},
{ value: 2 ,  label:"بنك فيصل الاسلامي"},
{ value: 3 ,  label:"البنك الزراعي السوداني"},
{ value: 4 ,  label:"بنك الخرطوم"},
{ value: 5 ,  label:"بنك النيلين"},
{ value: 6 ,  label:"بنك الادخار والتنمية الاجتماعية"},
{ value: 7 ,  label:"بنك ابوظبي الوطني"},
{ value: 8 ,  label:"بنك النيل "},
{ value: 11 ,  label:"البنك السوداني الفرنسي"},
{ value: 12 ,  label:"البنك الاهلي السوداني"},
{ value: 13 ,  label:"بنك التضامن الاسلامي"},
{ value: 14 ,  label:"البنك الاسلامي السوداني"},
{ value: 15 ,  label:"بنك النيل الازرق المشرق "},
{ value: 16 ,  label:"بنك البركة السوداني"},
{ value: 18 ,  label:"البنك السعودي السوداني"},
{ value: 19 ,  label:"بنك العمال الوطني"},
{ value: 20 ,  label:"بنك الشمال الاسلامي"},
{ value: 21 ,  label:"البنك العقاري السوداني"},
{ value: 22 ,  label:"بنك المزارع التجاري"},
{ value: 23 ,  label:"بنك الثروة الحيوانية"},
{ value: 24 ,  label:"بنك امدرمان الوطني"},
{ value: 25 ,  label:"بنك آيفوري"},
{ value: 27 ,  label:"بنك الاستثمار المالي"},
{ value: 28 ,  label:"مصرف الساحل والصحراء"},
{ value: 29 ,  label:"بنك السلام"},
{ value: 31 ,  label:"بنك تنمية الصادرات"},
{ value: 32 ,  label:"البنك السوداني المصري"},
{ value: 33 ,  label:"بنك الأسرة"},
{ value: 34 ,  label:"بنك الجزيرة السوداني الأردني"},
{ value: 35 ,  label:"بنك التنمية الصناعية"},
{ value: 36 ,  label:"بنك المال"},
{ value: 37 ,  label:"بنك بيبلوس"},
{ value: 40 ,  label:"البنك العربي السوداني"},
{ value: 41 ,  label:"البنك الأهلي المصري"},
{ value: 42 ,  label:"بنك قطر الوطني"},
{ value: 43 ,  label:"بنك قطر الإسلامي"},
{ value: 44 ,  label:"بنك أبوظبي الإسلامي"},
{ value: 45 ,  label:"بنك الرواد للتنمية"},
{ value: 56 ,  label:"بنك الخليج"},
    ]),
    BankLookup: types.optional(types.frozen(), [
      //name key is must.It is to show the text in front
{ id: 1 ,  name:"بنك السودان المركزى"},
{ id: 2 ,  name:"بنك فيصل الاسلامي"},
{ id: 3 ,  name:"البنك الزراعي السوداني"},
{ id: 4 ,  name:"بنك الخرطوم"},
{ id: 5 ,  name:"بنك النيلين"},
{ id: 6 ,  name:"بنك الادخار والتنمية الاجتماعية"},
{ id: 7 ,  name:"بنك ابوظبي الوطني"},
{ id: 8 ,  name:"بنك النيل "},
{ id: 11 ,  name:"البنك السوداني الفرنسي"},
{ id: 12 ,  name:"البنك الاهلي السوداني"},
{ id: 13 ,  name:"بنك التضامن الاسلامي"},
{ id: 14 ,  name:"البنك الاسلامي السوداني"},
{ id: 15 ,  name:"بنك النيل الازرق المشرق "},
{ id: 16 ,  name:"بنك البركة السوداني"},
{ id: 18 ,  name:"البنك السعودي السوداني"},
{ id: 19 ,  name:"بنك العمال الوطني"},
{ id: 20 ,  name:"بنك الشمال الاسلامي"},
{ id: 21 ,  name:"البنك العقاري السوداني"},
{ id: 22 ,  name:"بنك المزارع التجاري"},
{ id: 23 ,  name:"بنك الثروة الحيوانية"},
{ id: 24 ,  name:"بنك امدرمان الوطني"},
{ id: 25 ,  name:"بنك آيفوري"},
{ id: 27 ,  name:"بنك الاستثمار المالي"},
{ id: 28 ,  name:"مصرف الساحل والصحراء"},
{ id: 29 ,  name:"بنك السلام"},
{ id: 31 ,  name:"بنك تنمية الصادرات"},
{ id: 32 ,  name:"البنك السوداني المصري"},
{ id: 33 ,  name:"بنك الأسرة"},
{ id: 34 ,  name:"بنك الجزيرة السوداني الأردني"},
{ id: 35 ,  name:"بنك التنمية الصناعية"},
{ id: 36 ,  name:"بنك المال"},
{ id: 37 ,  name:"بنك بيبلوس"},
{ id: 40 ,  name:"البنك العربي السوداني"},
{ id: 41 ,  name:"البنك الأهلي المصري"},
{ id: 42 ,  name:"بنك قطر الوطني"},
{ id: 43 ,  name:"بنك قطر الإسلامي"},
{ id: 44 ,  name:"بنك أبوظبي الإسلامي"},
{ id: 45 ,  name:"بنك الرواد للتنمية"},
{ id: 56 ,  name:"بنك الخليج"},
    ]),
    BranchLookup: types.optional(types.frozen(), [
      //name key is must.It is to show the text in front
{ id: 4 ,  name:"فرع الخرطوم جنوب" ,BankCode: 4},
{ id: 9 ,  name:"كنانة" ,BankCode: 5},
{ id: 55 ,  name:"الرئاسة" ,BankCode: 8},
{ id: 59 ,  name:"الضعين" ,BankCode: 8},
{ id: 62 ,  name:"السجانة" ,BankCode: 8},
{ id: 66 ,  name:"الفاشر" ,BankCode: 8},
{ id: 70 ,  name:"ام روابة" ,BankCode: 8},
{ id: 10 ,  name:"بابنوسة" ,BankCode: 5},
{ id: 115 ,  name:"توكيل السوق المحلى الخرطوم" ,BankCode: 12},
{ id: 119 ,  name:"سوق ليبيا" ,BankCode: 13},
{ id: 13 ,  name:"ابو جبيه" ,BankCode: 5},
{ id: 17 ,  name:"فرع الادارة العامة للنقد الاجنبي" ,BankCode: 5},
{ id: 21 ,  name:"فرع عطبرة" ,BankCode: 5},
{ id: 25 ,  name:"فرع تندلتي" ,BankCode: 5},
{ id: 71 ,  name:"خشم القربة" ,BankCode: 8},
{ id: 73 ,  name:"الدبة" ,BankCode: 8},
{ id: 28 ,  name:"فرع سنار" ,BankCode: 5},
{ id: 31 ,  name:"فرع ودمدني" ,BankCode: 5},
{ id: 78 ,  name:"ام درمان السوق" ,BankCode: 8},
{ id: 35 ,  name:"فرع المنطقة الصناعية بحري" ,BankCode: 5},
{ id: 81 ,  name:"الابيض" ,BankCode: 8},
{ id: 85 ,  name:"(2 )الخرطوم" ,BankCode: 11},
{ id: 89 ,  name:"حلفا الجديدة" ,BankCode: 11},
{ id: 39 ,  name:"كبكابية" ,BankCode: 5},
{ id: 43 ,  name:"فرع  الامم المتحدة" ,BankCode: 5},
{ id: 128 ,  name:"سعد قشره" ,BankCode: 13},
{ id: 48 ,  name:"فرع السوق العربي" ,BankCode: 5},
{ id: 134 ,  name:"السجانة" ,BankCode: 13},
{ id: 51 ,  name:"عطبره" ,BankCode: 8},
{ id: 136 ,  name:"السوق العربى" ,BankCode: 13},
{ id: 281 ,  name:"حلفا الجديدة" ,BankCode: 22},
{ id: 284 ,  name:"المسعودية" ,BankCode: 22},
{ id: 138 ,  name:"الصناعات بورتسودان" ,BankCode: 14},
{ id: 291 ,  name:"شمبات" ,BankCode: 22},
{ id: 293 ,  name:"بحرى المنطقة" ,BankCode: 22},
{ id: 143 ,  name:"الاسر القرش" ,BankCode: 14},
{ id: 147 ,  name:"سنجة" ,BankCode: 14},
{ id: 150 ,  name:"كوستى" ,BankCode: 14},
{ id: 153 ,  name:"السوق العربى" ,BankCode: 14},
{ id: 156 ,  name:"الدندر" ,BankCode: 14},
{ id: 159 ,  name:"كسلا" ,BankCode: 14},
{ id: 97 ,  name:"المناقل" ,BankCode: 11},
{ id: 101 ,  name:"مدنى" ,BankCode: 11},
{ id: 104 ,  name:"كوستى" ,BankCode: 12},
{ id: 107 ,  name:"توكيل السوق الشعبى امدرمان" ,BankCode: 12},
{ id: 164 ,  name:"الصناعات بحرى" ,BankCode: 14},
{ id: 333 ,  name:"سوق ليبيا" ,BankCode: 24},
{ id: 299 ,  name:"النهود" ,BankCode: 23},
{ id: 302 ,  name:"بورتسودان" ,BankCode: 23},
{ id: 336 ,  name:"المقرن " ,BankCode: 24},
{ id: 337 ,  name:"السجانة" ,BankCode: 24},
{ id: 172 ,  name:"الخرطوم" ,BankCode: 14},
{ id: 308 ,  name:"الجنينة" ,BankCode: 23},
{ id: 174 ,  name:"المناقل" ,BankCode: 14},
{ id: 313 ,  name:"سوق ليبيا" ,BankCode: 23},
{ id: 315 ,  name:"الفولة" ,BankCode: 23},
{ id: 342 ,  name:"الفرع الرئيسى" ,BankCode: 27},
{ id: 320 ,  name:"المنطقة الحرة" ,BankCode: 24},
{ id: 322 ,  name:"جوبا" ,BankCode: 24},
{ id: 344 ,  name:"فرع الامم المتحدة" ,BankCode: 6},
{ id: 181 ,  name:"بورتسودان" ,BankCode: 15},
{ id: 328 ,  name:"بورتسودان" ,BankCode: 24},
{ id: 347 ,  name:"الرئاسة " ,BankCode: 20},
{ id: 349 ,  name:"النيل" ,BankCode: 4},
{ id: 383 ,  name:"الرئاسة" ,BankCode: 31},
{ id: 351 ,  name:"البرلمان" ,BankCode: 4},
{ id: 387 ,  name:"بنك الأسرة -فرع عطبرة " ,BankCode: 33},
{ id: 389 ,  name:"فرع جوبا" ,BankCode: 1},
{ id: 354 ,  name:"بنك الامارات والسودان" ,BankCode: 30},
{ id: 191 ,  name:"الحصاحيصا" ,BankCode: 16},
{ id: 193 ,  name:"الخرطوم جنوب" ,BankCode: 16},
{ id: 361 ,  name:"المقرن" ,BankCode: 4},
{ id: 364 ,  name:"فرع الابيض" ,BankCode: 31},
{ id: 197 ,  name:"السوق العربى" ,BankCode: 16},
{ id: 368 ,  name:"الفاشر" ,BankCode: 4},
{ id: 370 ,  name:"فرع بورتسودان-الصادرات" ,BankCode: 31},
{ id: 202 ,  name:"الحرفيين" ,BankCode: 16},
{ id: 372 ,  name:"الفرع المصرفى الخاص" ,BankCode: 15},
{ id: 397 ,  name:"دنقلا" ,BankCode: 1},
{ id: 399 ,  name:"الأبيض" ,BankCode: 1},
{ id: 207 ,  name:"بورتسودان" ,BankCode: 17},
{ id: 208 ,  name:"سوق ليبيا" ,BankCode: 17},
{ id: 210 ,  name:"الامم المتحدة" ,BankCode: 17},
{ id: 411 ,  name:"فرع المحطة الوسطي الخرطوم" ,BankCode: 2},
{ id: 376 ,  name:"فرع الجنينة" ,BankCode: 1},
{ id: 414 ,  name:"بورتسودان" ,BankCode: 2},
{ id: 378 ,  name:"فرع كادقلى" ,BankCode: 1},
{ id: 216 ,  name:"بحرى" ,BankCode: 17},
{ id: 423 ,  name:"فرع السوق الشعبي امدرمان" ,BankCode: 2},
{ id: 219 ,  name:"الحصاحيصا" ,BankCode: 18},
{ id: 437 ,  name:"فرع حلة كوكو" ,BankCode: 2},
{ id: 441 ,  name:"24القرشي" ,BankCode: 3},
{ id: 493 ,  name:"تندلتي" ,BankCode: 3},
{ id: 496 ,  name:"فرع الخرطوم بحري" ,BankCode: 3},
{ id: 445 ,  name:"لقاوة" ,BankCode: 3},
{ id: 447 ,  name:"الرهد" ,BankCode: 3},
{ id: 501 ,  name:"قارسيلا" ,BankCode: 3},
{ id: 433 ,  name:"فرع السوق الشعبي الخرطوم" ,BankCode: 2},
{ id: 451 ,  name:"سنجة" ,BankCode: 3},
{ id: 455 ,  name:"فرع العيلفون" ,BankCode: 3},
{ id: 458 ,  name:"اللعيت جار النبي" ,BankCode: 3},
{ id: 506 ,  name:"الهدي" ,BankCode: 3},
{ id: 509 ,  name:"كاس" ,BankCode: 3},
{ id: 512 ,  name:"الفاشر" ,BankCode: 3},
{ id: 464 ,  name:"عطبرة" ,BankCode: 3},
{ id: 551 ,  name:"كادقلى" ,BankCode: 4},
{ id: 553 ,  name:"كسلا" ,BankCode: 4},
{ id: 556 ,  name:"الابيض" ,BankCode: 4},
{ id: 557 ,  name:"القضارف" ,BankCode: 4},
{ id: 559 ,  name:"بورتسودان" ,BankCode: 4},
{ id: 517 ,  name:"كتم" ,BankCode: 3},
{ id: 521 ,  name:"الحصاحيصا" ,BankCode: 3},
{ id: 524 ,  name:"الضعين" ,BankCode: 3},
{ id: 474 ,  name:"الدامر" ,BankCode: 3},
{ id: 563 ,  name:"الضعين" ,BankCode: 4},
{ id: 565 ,  name:"الفاشر" ,BankCode: 4},
{ id: 530 ,  name:"الجنينة" ,BankCode: 3},
{ id: 534 ,  name:"طوكر" ,BankCode: 3},
{ id: 537 ,  name:"الرنك" ,BankCode: 4},
{ id: 481 ,  name:"تنقاسي" ,BankCode: 3},
{ id: 484 ,  name:"الشريك" ,BankCode: 3},
{ id: 487 ,  name:"القضارف" ,BankCode: 3},
{ id: 542 ,  name:"دنقلا" ,BankCode: 4},
{ id: 545 ,  name:"مروى" ,BankCode: 4},
{ id: 548 ,  name:"الدامر" ,BankCode: 4},
{ id: 570 ,  name:"سنار" ,BankCode: 4},
{ id: 574 ,  name:"حلفا الجديدة" ,BankCode: 4},
{ id: 606 ,  name:"الرئاسة" ,BankCode: 38},
{ id: 610 ,  name:"سوق امدرمان" ,BankCode: 16},
{ id: 614 ,  name:"الرئاسة" ,BankCode: 43},
{ id: 578 ,  name:"فرع البقعة امدرمان" ,BankCode: 4},
{ id: 582 ,  name:"فرع المنطقة الصناعية بحري" ,BankCode: 4},
{ id: 586 ,  name:"فرع السوق المحلي" ,BankCode: 4},
{ id: 590 ,  name:"فرع شارع الجامعة" ,BankCode: 4},
{ id: 620 ,  name:"الاضية" ,BankCode: 8},
{ id: 623 ,  name:"فرع المنطقة الصناعية" ,BankCode: 6},
{ id: 594 ,  name:"فرع المنشية " ,BankCode: 2},
{ id: 597 ,  name:"الأمم المتحدة " ,BankCode: 20},
{ id: 661 ,  name:"فرع الخرطوم" ,BankCode: 32},
{ id: 663 ,  name:"فرع ليبيا" ,BankCode: 32},
{ id: 666 ,  name:"الفرع الخاص" ,BankCode: 32},
{ id: 668 ,  name:"السوق الشعبي أم درمان" ,BankCode: 34},
{ id: 671 ,  name:"بحري" ,BankCode: 34},
{ id: 756 ,  name:"بحري" ,BankCode: 20},
{ id: 759 ,  name:"شارع محمد نجيب" ,BankCode: 24},
{ id: 763 ,  name:"بورتسودان" ,BankCode: 56},
{ id: 674 ,  name:"السوق المحلي" ,BankCode: 34},
{ id: 678 ,  name:"الكلاكلة" ,BankCode: 34},
{ id: 682 ,  name:"برج الجزيرة" ,BankCode: 34},
{ id: 627 ,  name:"قري" ,BankCode: 15},
{ id: 768 ,  name:"كسلا" ,BankCode: 24},
{ id: 771 ,  name:"محمد نجيب" ,BankCode: 14},
{ id: 631 ,  name:"سوق ليبيا" ,BankCode: 15},
{ id: 635 ,  name:"القضارف" ,BankCode: 17},
{ id: 639 ,  name:"عبيد ختم" ,BankCode: 17},
{ id: 643 ,  name:"عبيد ختم" ,BankCode: 19},
{ id: 775 ,  name:"الجنينة" ,BankCode: 8},
{ id: 777 ,  name:"فرع كسلا" ,BankCode: 34},
{ id: 653 ,  name:"ملكال" ,BankCode: 25},
{ id: 780 ,  name:"الكرين بحري" ,BankCode: 14},
{ id: 782 ,  name:"السوق المحلي" ,BankCode: 18},
{ id: 686 ,  name:"أمدرمان" ,BankCode: 35},
{ id: 691 ,  name:"بحري" ,BankCode: 42},
{ id: 695 ,  name:"الرياض" ,BankCode: 42},
{ id: 699 ,  name:"الفتيحاب" ,BankCode: 2},
{ id: 703 ,  name:"السوق المحلي" ,BankCode: 11},
{ id: 707 ,  name:"سعد قشرة" ,BankCode: 14},
{ id: 711 ,  name:"الأكاديمية" ,BankCode: 23},
{ id: 716 ,  name:"جبرة" ,BankCode: 14},
{ id: 720 ,  name:"الخرطوم 2" ,BankCode: 20},
{ id: 724 ,  name:"العمارات" ,BankCode: 21},
{ id: 728 ,  name:"فرع سوق ليبيا          " ,BankCode: 6},
{ id: 732 ,  name:"بورتسودان" ,BankCode: 45},
{ id: 736 ,  name:"حلة كوكو" ,BankCode: 8},
{ id: 740 ,  name:"بحري" ,BankCode: 2},
{ id: 744 ,  name:"شمبات" ,BankCode: 8},
{ id: 749 ,  name:" كرري" ,BankCode: 13},
{ id: 224 ,  name:"الخرطوم" ,BankCode: 18},
{ id: 228 ,  name:"بورتسودان" ,BankCode: 18},
{ id: 232 ,  name:"ربك" ,BankCode: 19},
{ id: 236 ,  name:"الرئيسى" ,BankCode: 19},
{ id: 240 ,  name:"السوق العربى" ,BankCode: 19},
{ id: 244 ,  name:"دنقلا" ,BankCode: 20},
{ id: 248 ,  name:"السوق الشعبى" ,BankCode: 20},
{ id: 252 ,  name:"الصناعات بحرى" ,BankCode: 20},
{ id: 256 ,  name:"كوستى" ,BankCode: 20},
{ id: 260 ,  name:"الخرطوم" ,BankCode: 20},
{ id: 265 ,  name:"مدنى" ,BankCode: 21},
{ id: 270 ,  name:"دنقلا" ,BankCode: 22},
{ id: 274 ,  name:"الرنك" ,BankCode: 22},
{ id: 5 ,  name:"فرع الجمهورية" ,BankCode: 4},
{ id: 53 ,  name:"مدنى" ,BankCode: 8},
{ id: 56 ,  name:"الخرطوم" ,BankCode: 8},
{ id: 60 ,  name:"امدرمان السوق الشعبى" ,BankCode: 8},
{ id: 63 ,  name:"الامم المتحدة" ,BankCode: 8},
{ id: 67 ,  name:"بربر" ,BankCode: 8},
{ id: 111 ,  name:"سنار" ,BankCode: 12},
{ id: 11 ,  name:"الرهد" ,BankCode: 5},
{ id: 116 ,  name:"القضارف" ,BankCode: 12},
{ id: 120 ,  name:"كريمة" ,BankCode: 13},
{ id: 14 ,  name:"الضعين" ,BankCode: 5},
{ id: 18 ,  name:"فرع نيالا" ,BankCode: 5},
{ id: 22 ,  name:"فرع دنقلا" ,BankCode: 5},
{ id: 26 ,  name:"فرع القطينة" ,BankCode: 5},
{ id: 124 ,  name:"القضارف" ,BankCode: 13},
{ id: 126 ,  name:"بورتسودان" ,BankCode: 13},
{ id: 29 ,  name:"فرع ربك" ,BankCode: 5},
{ id: 76 ,  name:"النهود" ,BankCode: 8},
{ id: 33 ,  name:"فرع الابيض" ,BankCode: 5},
{ id: 36 ,  name:"فرع حلة كوكو" ,BankCode: 5},
{ id: 82 ,  name:"الخرطوم" ,BankCode: 9},
{ id: 86 ,  name:"الفرع الرئيسى" ,BankCode: 11},
{ id: 90 ,  name:"نيالا" ,BankCode: 11},
{ id: 40 ,  name:"المناقل" ,BankCode: 5},
{ id: 44 ,  name:"فرع السجانة" ,BankCode: 5},
{ id: 129 ,  name:"البرلمان" ,BankCode: 13},
{ id: 131 ,  name:"كوستى" ,BankCode: 13},
{ id: 49 ,  name:"فرع العمارات" ,BankCode: 5},
{ id: 52 ,  name:"دنقلا" ,BankCode: 8},
{ id: 278 ,  name:"مدنى" ,BankCode: 22},
{ id: 282 ,  name:"كسلا" ,BankCode: 22},
{ id: 285 ,  name:"بحرى السوق" ,BankCode: 22},
{ id: 288 ,  name:"سنار" ,BankCode: 22},
{ id: 140 ,  name:"البرقيق" ,BankCode: 14},
{ id: 294 ,  name:"امدرمان حى العرب" ,BankCode: 22},
{ id: 144 ,  name:"رفاعة" ,BankCode: 14},
{ id: 148 ,  name:"دنقلا" ,BankCode: 14},
{ id: 151 ,  name:"نيالا" ,BankCode: 14},
{ id: 154 ,  name:"وادى حلفا" ,BankCode: 14},
{ id: 157 ,  name:"الغابة" ,BankCode: 14},
{ id: 160 ,  name:"الدويم" ,BankCode: 14},
{ id: 98 ,  name:"الدمازين" ,BankCode: 11},
{ id: 102 ,  name:"مدنى" ,BankCode: 12},
{ id: 162 ,  name:"الدمازين" ,BankCode: 14},
{ id: 108 ,  name:"الثورة" ,BankCode: 12},
{ id: 165 ,  name:"الفرع الرئيسى" ,BankCode: 14},
{ id: 297 ,  name:"السوق العربى" ,BankCode: 22},
{ id: 334 ,  name:"الصناعات الصغيرة" ,BankCode: 24},
{ id: 303 ,  name:"امدرمان" ,BankCode: 23},
{ id: 170 ,  name:"مدنى" ,BankCode: 14},
{ id: 305 ,  name:"الفرع الرئيسى" ,BankCode: 23},
{ id: 307 ,  name:"السوق المحلى" ,BankCode: 23},
{ id: 309 ,  name:"الشعبى امدرمان" ,BankCode: 23},
{ id: 340 ,  name:"مكتب صرف امدرمان" ,BankCode: 25},
{ id: 341 ,  name:"الخرطوم" ,BankCode: 25},
{ id: 316 ,  name:"حمرة الشيخ" ,BankCode: 23},
{ id: 318 ,  name:"الابيض" ,BankCode: 23},
{ id: 179 ,  name:"امدرمان" ,BankCode: 15},
{ id: 323 ,  name:"الدمازين" ,BankCode: 24},
{ id: 325 ,  name:"الابيض" ,BankCode: 24},
{ id: 327 ,  name:"القضارف" ,BankCode: 24},
{ id: 329 ,  name:"امدرمان" ,BankCode: 24},
{ id: 331 ,  name:"بنت خويلد" ,BankCode: 24},
{ id: 332 ,  name:"الخرطوم" ,BankCode: 24},
{ id: 384 ,  name:"فرع كسلا" ,BankCode: 6},
{ id: 386 ,  name:"فرع الامم المتحدة" ,BankCode: 8},
{ id: 353 ,  name:"الجمهورية" ,BankCode: 4},
{ id: 390 ,  name:"فرع ملكال" ,BankCode: 1},
{ id: 355 ,  name:"فرع البرلمان" ,BankCode: 5},
{ id: 357 ,  name:"الفرع الرئيسي" ,BankCode: 22},
{ id: 359 ,  name:"البنك السوداني المصري-الفرع الرئيسى" ,BankCode: 32},
{ id: 362 ,  name:"السوق المحلي" ,BankCode: 31},
{ id: 365 ,  name:"فرع الخرطوم" ,BankCode: 36},
{ id: 198 ,  name:"البرج" ,BankCode: 16},
{ id: 199 ,  name:"الزهراء" ,BankCode: 16},
{ id: 394 ,  name:"فرع كادقلى " ,BankCode: 4},
{ id: 395 ,  name:"فرع الموردة " ,BankCode: 2},
{ id: 396 ,  name:"مدنى" ,BankCode: 1},
{ id: 374 ,  name:"فرع الرياض -المشتل" ,BankCode: 4},
{ id: 400 ,  name:"عطبرة" ,BankCode: 1},
{ id: 403 ,  name:"الرئاسة" ,BankCode: 1},
{ id: 406 ,  name:"فرع امدرمان المحطة الوسطي" ,BankCode: 2},
{ id: 409 ,  name:"الصناعية الخرطوم" ,BankCode: 2},
{ id: 375 ,  name:"العمارات" ,BankCode: 16},
{ id: 413 ,  name:"فرع السجانة" ,BankCode: 2},
{ id: 415 ,  name:"الابيض" ,BankCode: 2},
{ id: 419 ,  name:"القضارف" ,BankCode: 2},
{ id: 380 ,  name:"فرع الدمازين" ,BankCode: 1},
{ id: 424 ,  name:"كوستى" ,BankCode: 2},
{ id: 220 ,  name:"الابيض" ,BankCode: 18},
{ id: 438 ,  name:"كسلا" ,BankCode: 2},
{ id: 491 ,  name:"حجر العسل" ,BankCode: 3},
{ id: 494 ,  name:"الهلالية" ,BankCode: 3},
{ id: 497 ,  name:"النهود" ,BankCode: 3},
{ id: 429 ,  name:"فرع السوق المحلي" ,BankCode: 2},
{ id: 430 ,  name:"فرع العربي الخرطوم" ,BankCode: 2},
{ id: 448 ,  name:"المجلد" ,BankCode: 3},
{ id: 434 ,  name:"عطبره" ,BankCode: 2},
{ id: 452 ,  name:"بارا" ,BankCode: 3},
{ id: 503 ,  name:"دوكة" ,BankCode: 3},
{ id: 504 ,  name:"رهيد البردي" ,BankCode: 3},
{ id: 507 ,  name:"الدويم" ,BankCode: 3},
{ id: 510 ,  name:"ملكال" ,BankCode: 3},
{ id: 549 ,  name:"مليط" ,BankCode: 4},
{ id: 550 ,  name:"واو" ,BankCode: 4},
{ id: 467 ,  name:"جزيرة شيري" ,BankCode: 3},
{ id: 554 ,  name:"الدلنج" ,BankCode: 4},
{ id: 469 ,  name:"وادي حلفا" ,BankCode: 3},
{ id: 515 ,  name:"ام كدادة" ,BankCode: 3},
{ id: 560 ,  name:"الدندر" ,BankCode: 4},
{ id: 518 ,  name:"العزازي" ,BankCode: 3},
{ id: 472 ,  name:"فرع حلة كوكو" ,BankCode: 3},
{ id: 473 ,  name:"الدبة" ,BankCode: 3},
{ id: 562 ,  name:"الجنينة" ,BankCode: 4},
{ id: 528 ,  name:"الدندر" ,BankCode: 3},
{ id: 566 ,  name:"النهود" ,BankCode: 4},
{ id: 531 ,  name:"الكاملين" ,BankCode: 3},
{ id: 477 ,  name:"ودحامد" ,BankCode: 3},
{ id: 478 ,  name:"فرع السوق المركزي الخرطوم" ,BankCode: 3},
{ id: 482 ,  name:"العبيدية" ,BankCode: 3},
{ id: 485 ,  name:"شندي" ,BankCode: 3},
{ id: 540 ,  name:"جوبا" ,BankCode: 4},
{ id: 543 ,  name:"ابوحمد" ,BankCode: 4},
{ id: 546 ,  name:"كريمة" ,BankCode: 4},
{ id: 568 ,  name:"عسلاية" ,BankCode: 4},
{ id: 571 ,  name:"رفاعة" ,BankCode: 4},
{ id: 575 ,  name:"مدنى" ,BankCode: 4},
{ id: 607 ,  name:"الرئاسة" ,BankCode: 41},
{ id: 611 ,  name:"الرئاسة" ,BankCode: 24},
{ id: 615 ,  name:"الرئاسة" ,BankCode: 44},
{ id: 579 ,  name:"فرع المحطة الوسطي امدرمان" ,BankCode: 4},
{ id: 583 ,  name:"بربر" ,BankCode: 4},
{ id: 587 ,  name:"فرع الموردة" ,BankCode: 4},
{ id: 591 ,  name:"فرع الخرطوم 2" ,BankCode: 4},
{ id: 592 ,  name:"فرع السجانة" ,BankCode: 4},
{ id: 624 ,  name:"الفرع الرئيسي" ,BankCode: 6},
{ id: 659 ,  name:"أم درمان" ,BankCode: 31},
{ id: 660 ,  name:"العمارات" ,BankCode: 31},
{ id: 600 ,  name:"السجانة" ,BankCode: 22},
{ id: 603 ,  name:"الرئاسة" ,BankCode: 40},
{ id: 751 ,  name:"الموردة" ,BankCode: 34},
{ id: 669 ,  name:"فرع مدني" ,BankCode: 34},
{ id: 672 ,  name:"بورتسودان" ,BankCode: 34},
{ id: 757 ,  name:"حلة كوكو" ,BankCode: 24},
{ id: 760 ,  name:"ربك" ,BankCode: 24},
{ id: 764 ,  name:"جامعة السودان" ,BankCode: 24},
{ id: 675 ,  name:"سوق ليبيا" ,BankCode: 34},
{ id: 679 ,  name:"العمارات" ,BankCode: 34},
{ id: 683 ,  name:"بورتسودان" ,BankCode: 35},
{ id: 628 ,  name:"توتي" ,BankCode: 15},
{ id: 769 ,  name:" القضارف" ,BankCode: 15},
{ id: 772 ,  name:"الأمن الإقتصادي" ,BankCode: 57},
{ id: 632 ,  name:"الجنينة" ,BankCode: 15},
{ id: 636 ,  name:"السجانه" ,BankCode: 17},
{ id: 640 ,  name:"الجنينة" ,BankCode: 17},
{ id: 644 ,  name:"توكيل الرازي" ,BankCode: 19},
{ id: 649 ,  name:"سوق القضارف" ,BankCode: 21},
{ id: 651 ,  name:"واو" ,BankCode: 25},
{ id: 654 ,  name:"أم درمان" ,BankCode: 29},
{ id: 656 ,  name:"عبيد ختم" ,BankCode: 31},
{ id: 783 ,  name:"سوق ليبيا" ,BankCode: 18},
{ id: 687 ,  name:"بحري" ,BankCode: 37},
{ id: 692 ,  name:"الحرية" ,BankCode: 42},
{ id: 696 ,  name:"الزبير باشا" ,BankCode: 2},
{ id: 700 ,  name:"ليبيا" ,BankCode: 11},
{ id: 704 ,  name:"السوق الشعبي" ,BankCode: 13},
{ id: 708 ,  name:"قري" ,BankCode: 16},
{ id: 712 ,  name:"عطبرة" ,BankCode: 24},
{ id: 717 ,  name:"العرضة" ,BankCode: 28},
{ id: 721 ,  name:"شندي" ,BankCode: 2},
{ id: 725 ,  name:"أمدرمان" ,BankCode: 21},
{ id: 729 ,  name:"كسلا" ,BankCode: 20},
{ id: 733 ,  name:"اوماك" ,BankCode: 45},
{ id: 737 ,  name:"البرلمان" ,BankCode: 8},
{ id: 741 ,  name:"الأبيض" ,BankCode: 15},
{ id: 745 ,  name:"مدني" ,BankCode: 24},
{ id: 750 ,  name:"إدارة التمويل بالتجزئة" ,BankCode: 2},
{ id: 225 ,  name:"كوستى" ,BankCode: 18},
{ id: 229 ,  name:"سعد قشرة" ,BankCode: 18},
{ id: 233 ,  name:"سوق ليبيا" ,BankCode: 19},
{ id: 237 ,  name:"كوستى" ,BankCode: 19},
{ id: 241 ,  name:"القضارف" ,BankCode: 19},
{ id: 245 ,  name:"القضارف" ,BankCode: 20},
{ id: 249 ,  name:"امدرمان" ,BankCode: 20},
{ id: 253 ,  name:"البرج" ,BankCode: 20},
{ id: 257 ,  name:"السجانة" ,BankCode: 20},
{ id: 262 ,  name:"نيالا" ,BankCode: 21},
{ id: 267 ,  name:"الطيار مراد" ,BankCode: 21},
{ id: 271 ,  name:"نيالا" ,BankCode: 22},
{ id: 275 ,  name:"كوستى" ,BankCode: 22},
{ id: 6 ,  name:"فرع شارع الحرية" ,BankCode: 4},
{ id: 110 ,  name:"امدرمان" ,BankCode: 12},
{ id: 57 ,  name:"بورتسودان" ,BankCode: 8},
{ id: 61 ,  name:"ربك" ,BankCode: 8},
{ id: 64 ,  name:"سنار" ,BankCode: 8},
{ id: 68 ,  name:"كوستى" ,BankCode: 8},
{ id: 112 ,  name:"كسلا" ,BankCode: 12},
{ id: 12 ,  name:"كريمة" ,BankCode: 5},
{ id: 117 ,  name:"توكيل المنطقة الصناعية الخرطوم" ,BankCode: 12},
{ id: 121 ,  name:"الضعين" ,BankCode: 13},
{ id: 15 ,  name:"امدرمان الوسطى" ,BankCode: 5},
{ id: 19 ,  name:"فرع كادقلي" ,BankCode: 5},
{ id: 23 ,  name:"فرع الكاملين" ,BankCode: 5},
{ id: 27 ,  name:"فرع شندي" ,BankCode: 5},
{ id: 72 ,  name:"ابو جبيهه" ,BankCode: 8},
{ id: 74 ,  name:"كريمة" ,BankCode: 8},
{ id: 30 ,  name:"فرع كوستي" ,BankCode: 5},
{ id: 32 ,  name:"حلة كوكو" ,BankCode: 5},
{ id: 79 ,  name:"نيالا" ,BankCode: 8},
{ id: 37 ,  name:"السوق المحلى" ,BankCode: 5},
{ id: 83 ,  name:"الخرطوم" ,BankCode: 10},
{ id: 87 ,  name:"ربك" ,BankCode: 11},
{ id: 91 ,  name:"الابيض" ,BankCode: 11},
{ id: 41 ,  name:"حلفا الجديدة" ,BankCode: 5},
{ id: 45 ,  name:"فرع المصرف النموذجي" ,BankCode: 5},
{ id: 47 ,  name:"فرع الرياض" ,BankCode: 5},
{ id: 132 ,  name:"الرهد" ,BankCode: 13},
{ id: 135 ,  name:"سنار" ,BankCode: 13},
{ id: 276 ,  name:"المعيلق" ,BankCode: 22},
{ id: 279 ,  name:"الفاو" ,BankCode: 22},
{ id: 137 ,  name:"الرئاسة" ,BankCode: 14},
{ id: 286 ,  name:"السوق الافرنجى" ,BankCode: 22},
{ id: 289 ,  name:"الجمهورية" ,BankCode: 22},
{ id: 292 ,  name:"الابيض" ,BankCode: 22},
{ id: 295 ,  name:"امدرمان السوق" ,BankCode: 22},
{ id: 145 ,  name:"البلدية" ,BankCode: 14},
{ id: 92 ,  name:"القضارف" ,BankCode: 11},
{ id: 93 ,  name:"بورتسودان" ,BankCode: 11},
{ id: 155 ,  name:"الابيض" ,BankCode: 14},
{ id: 158 ,  name:"الخرطوم جنوب" ,BankCode: 14},
{ id: 296 ,  name:"الدامر" ,BankCode: 22},
{ id: 99 ,  name:"امدرمان" ,BankCode: 11},
{ id: 161 ,  name:"سنار" ,BankCode: 14},
{ id: 105 ,  name:"بحرى" ,BankCode: 12},
{ id: 163 ,  name:"السوق الشعبى امدرمان" ,BankCode: 14},
{ id: 166 ,  name:"كرمة النزل" ,BankCode: 14},
{ id: 168 ,  name:"السجانة" ,BankCode: 14},
{ id: 300 ,  name:"الضعين" ,BankCode: 23},
{ id: 335 ,  name:"السوق المحلى" ,BankCode: 24},
{ id: 304 ,  name:"الطيار مراد" ,BankCode: 23},
{ id: 306 ,  name:"السجانة" ,BankCode: 23},
{ id: 339 ,  name:"الرنك" ,BankCode: 25},
{ id: 310 ,  name:"القضارف" ,BankCode: 23},
{ id: 312 ,  name:"ربك" ,BankCode: 23},
{ id: 176 ,  name:"بورتسودان" ,BankCode: 14},
{ id: 317 ,  name:"كسلا" ,BankCode: 23},
{ id: 319 ,  name:"دنقلا" ,BankCode: 23},
{ id: 343 ,  name:"الرئاسة" ,BankCode: 28},
{ id: 324 ,  name:"سنار" ,BankCode: 24},
{ id: 345 ,  name:"بنت خويلد" ,BankCode: 24},
{ id: 182 ,  name:"دنقلا" ,BankCode: 16},
{ id: 330 ,  name:"القيادة العامة" ,BankCode: 24},
{ id: 348 ,  name:"الرئاسة" ,BankCode: 29},
{ id: 185 ,  name:"أم روابة" ,BankCode: 16},
{ id: 385 ,  name:"فرع دنقلا " ,BankCode: 6},
{ id: 352 ,  name:"الجامعة" ,BankCode: 4},
{ id: 188 ,  name:"سنار" ,BankCode: 16},
{ id: 391 ,  name:"فرع واو" ,BankCode: 1},
{ id: 190 ,  name:"مدنى" ,BankCode: 16},
{ id: 192 ,  name:"المغتربين" ,BankCode: 16},
{ id: 194 ,  name:"الابيض" ,BankCode: 16},
{ id: 363 ,  name:"كوستي" ,BankCode: 6},
{ id: 196 ,  name:"الدمازين" ,BankCode: 16},
{ id: 367 ,  name:"ابوظبي العمارات شارع 15" ,BankCode: 7},
{ id: 393 ,  name:"كادقلى " ,BankCode: 8},
{ id: 201 ,  name:"سوق ليبيا" ,BankCode: 16},
{ id: 203 ,  name:"السجانة" ,BankCode: 16},
{ id: 205 ,  name:"غبيش" ,BankCode: 17},
{ id: 398 ,  name:"كوستى" ,BankCode: 1},
{ id: 401 ,  name:"الفاشر" ,BankCode: 1},
{ id: 404 ,  name:"القضارف" ,BankCode: 1},
{ id: 209 ,  name:"امدرمان" ,BankCode: 17},
{ id: 211 ,  name:"الفرع الرئيسى" ,BankCode: 17},
{ id: 412 ,  name:"فرع الفيحاء" ,BankCode: 2},
{ id: 214 ,  name:"الضعين" ,BankCode: 17},
{ id: 416 ,  name:"فرع جامعة الخرطوم" ,BankCode: 2},
{ id: 379 ,  name:"فرع كسلا" ,BankCode: 1},
{ id: 217 ,  name:"العمارات" ,BankCode: 18},
{ id: 426 ,  name:"فرع سوق ليبيا" ,BankCode: 2},
{ id: 382 ,  name:"الفرع الرئيسي" ,BankCode: 37},
{ id: 428 ,  name:"امدرمان الاسلامية العرضة" ,BankCode: 2},
{ id: 442 ,  name:"ام روابة" ,BankCode: 3},
{ id: 443 ,  name:"المزروب" ,BankCode: 3},
{ id: 444 ,  name:"نيالا" ,BankCode: 3},
{ id: 446 ,  name:"زالنجي" ,BankCode: 3},
{ id: 500 ,  name:"عد الفرسان" ,BankCode: 3},
{ id: 432 ,  name:"الفاشر" ,BankCode: 2},
{ id: 502 ,  name:"حمرة الوز" ,BankCode: 3},
{ id: 453 ,  name:"فرع جبل اولياء" ,BankCode: 3},
{ id: 456 ,  name:"الدلنج" ,BankCode: 3},
{ id: 459 ,  name:"الفرع الرئيسي" ,BankCode: 3},
{ id: 508 ,  name:"فرع الجديدة الثورة" ,BankCode: 3},
{ id: 511 ,  name:"سنار" ,BankCode: 3},
{ id: 462 ,  name:"حلفا الجديدة" ,BankCode: 3},
{ id: 465 ,  name:"الحواتة" ,BankCode: 3},
{ id: 552 ,  name:"كنانة" ,BankCode: 4},
{ id: 555 ,  name:"ام روابة" ,BankCode: 4},
{ id: 514 ,  name:"واو" ,BankCode: 3},
{ id: 558 ,  name:"الرهد" ,BankCode: 4},
{ id: 561 ,  name:"كركوج" ,BankCode: 4},
{ id: 519 ,  name:"الرنك" ,BankCode: 3},
{ id: 522 ,  name:"المزموم" ,BankCode: 3},
{ id: 525 ,  name:"الحوش" ,BankCode: 3},
{ id: 527 ,  name:"بنك الجزيرة السوداني الاردني-الفرع الرئيسي" ,BankCode: 34},
{ id: 476 ,  name:"كسلا" ,BankCode: 3},
{ id: 567 ,  name:"تندلتى" ,BankCode: 4},
{ id: 532 ,  name:"القطينة" ,BankCode: 3},
{ id: 535 ,  name:"شندى" ,BankCode: 4},
{ id: 479 ,  name:"كريمة" ,BankCode: 3},
{ id: 483 ,  name:"القولد" ,BankCode: 3},
{ id: 486 ,  name:"ابوحمد" ,BankCode: 3},
{ id: 488 ,  name:"فرع امدرمان" ,BankCode: 3},
{ id: 489 ,  name:"الحفير" ,BankCode: 3},
{ id: 490 ,  name:"بورتسودان" ,BankCode: 3},
{ id: 604 ,  name:"مطار الخرطوم" ,BankCode: 39},
{ id: 572 ,  name:"سنجة" ,BankCode: 4},
{ id: 576 ,  name:"غبيش" ,BankCode: 4},
{ id: 608 ,  name:"الفرع الرئيسي" ,BankCode: 5},
{ id: 612 ,  name:"الرئاسة" ,BankCode: 6},
{ id: 616 ,  name:"الرئاسة" ,BankCode: 45},
{ id: 580 ,  name:"فرع الانقاذ بحري" ,BankCode: 4},
{ id: 584 ,  name:"فرع البلدية بحري" ,BankCode: 4},
{ id: 588 ,  name:"ربك" ,BankCode: 4},
{ id: 618 ,  name:"الرياض" ,BankCode: 8},
{ id: 621 ,  name:"فرع أمدرمان" ,BankCode: 6},
{ id: 625 ,  name:"فرع بحري" ,BankCode: 6},
{ id: 595 ,  name:"فرع بحري" ,BankCode: 31},
{ id: 598 ,  name:"فرع مدني" ,BankCode: 6},
{ id: 601 ,  name:"شارع أفريقيا" ,BankCode: 23},
{ id: 664 ,  name:"بورتسودان" ,BankCode: 32},
{ id: 667 ,  name:"الفرع الرئيسي" ,BankCode: 34},
{ id: 754 ,  name:"كسلا" ,BankCode: 15},
{ id: 673 ,  name:"سعد قشرة" ,BankCode: 34},
{ id: 626 ,  name:"الرئاسة" ,BankCode: 8},
{ id: 761 ,  name:"شارع أفريقيا" ,BankCode: 56},
{ id: 765 ,  name:"شارع عبيد ختم" ,BankCode: 24},
{ id: 676 ,  name:"الطائف" ,BankCode: 34},
{ id: 680 ,  name:"الابيض" ,BankCode: 34},
{ id: 684 ,  name:"بحري" ,BankCode: 35},
{ id: 629 ,  name:"العمارات" ,BankCode: 15},
{ id: 770 ,  name:"شارع الستين" ,BankCode: 16},
{ id: 773 ,  name:"فرع جبره " ,BankCode: 24},
{ id: 633 ,  name:"الفاشر" ,BankCode: 15},
{ id: 637 ,  name:"السوق الشعبي أمدرمان" ,BankCode: 17},
{ id: 641 ,  name:"الرئاسة" ,BankCode: 17},
{ id: 645 ,  name:"شارع الستين" ,BankCode: 19},
{ id: 776 ,  name:"سعد قشرة" ,BankCode: 22},
{ id: 778 ,  name:"الخرطوم جنوب" ,BankCode: 35},
{ id: 779 ,  name:"قري السوق" ,BankCode: 14},
{ id: 781 ,  name:"الكلاكلة" ,BankCode: 22},
{ id: 784 ,  name:"فرع دنقلا" ,BankCode: 24},
{ id: 688 ,  name:"العمارات" ,BankCode: 37},
{ id: 693 ,  name:"الستين" ,BankCode: 42},
{ id: 697 ,  name:"قري" ,BankCode: 2},
{ id: 701 ,  name:"قاردن سيتي" ,BankCode: 11},
{ id: 705 ,  name:"الكلاكلة" ,BankCode: 13},
{ id: 709 ,  name:"السوق المحلي" ,BankCode: 16},
{ id: 714 ,  name:"السجانه" ,BankCode: 28},
{ id: 718 ,  name:"العمارات" ,BankCode: 2},
{ id: 722 ,  name:"ليبيا" ,BankCode: 14},
{ id: 726 ,  name:"فرع السوق العربى     " ,BankCode: 6},
{ id: 730 ,  name:"فرع الكدرو" ,BankCode: 11},
{ id: 734 ,  name:"الرئيسي" ,BankCode: 45},
{ id: 738 ,  name:"نقطة التجارة الخارجية" ,BankCode: 38},
{ id: 742 ,  name:"شارع محمد نجيب " ,BankCode: 8},
{ id: 746 ,  name:"كوستي" ,BankCode: 24},
{ id: 222 ,  name:"المحطة الوسطى" ,BankCode: 18},
{ id: 226 ,  name:"القضارف" ,BankCode: 18},
{ id: 230 ,  name:"الحرية" ,BankCode: 18},
{ id: 234 ,  name:"السوق المحلى" ,BankCode: 19},
{ id: 238 ,  name:"عطبره" ,BankCode: 19},
{ id: 242 ,  name:"ود مدنى" ,BankCode: 19},
{ id: 246 ,  name:"مدنى" ,BankCode: 20},
{ id: 250 ,  name:"صرف سوق 6" ,BankCode: 20},
{ id: 254 ,  name:"صرف الكلاكلة" ,BankCode: 20},
{ id: 258 ,  name:"الصناعية الخرطوم" ,BankCode: 20},
{ id: 263 ,  name:"الابيض" ,BankCode: 21},
{ id: 268 ,  name:"بحرى" ,BankCode: 21},
{ id: 272 ,  name:"النهود" ,BankCode: 22},
{ id: 3 ,  name:"فرع المنطقة الصناعية الخرطوم" ,BankCode: 4},
{ id: 7 ,  name:"فرع السوق العربي" ,BankCode: 4},
{ id: 54 ,  name:"حلفا الجديدة" ,BankCode: 8},
{ id: 58 ,  name:"بحرى السوق" ,BankCode: 8},
{ id: 221 ,  name:"السجانة" ,BankCode: 18},
{ id: 65 ,  name:"كسلا" ,BankCode: 8},
{ id: 69 ,  name:"المناقل" ,BankCode: 8},
{ id: 113 ,  name:"السوق العربى" ,BankCode: 12},
{ id: 114 ,  name:"توكيل السوق الشعبى الخرطوم" ,BankCode: 12},
{ id: 118 ,  name:"الخرطوم" ,BankCode: 12},
{ id: 122 ,  name:"الابيض" ,BankCode: 13},
{ id: 16 ,  name:"المجلد" ,BankCode: 5},
{ id: 20 ,  name:"النهود" ,BankCode: 5},
{ id: 24 ,  name:"فرع بورتسودان" ,BankCode: 5},
{ id: 123 ,  name:"نيالا" ,BankCode: 13},
{ id: 125 ,  name:"مدنى" ,BankCode: 13},
{ id: 127 ,  name:"امدرمان" ,BankCode: 13},
{ id: 75 ,  name:"القضارف" ,BankCode: 8},
{ id: 77 ,  name:"بحرى المنطقة الصناعية" ,BankCode: 8},
{ id: 34 ,  name:"فرع كرري" ,BankCode: 5},
{ id: 80 ,  name:"السوق المحلى" ,BankCode: 8},
{ id: 84 ,  name:"الخرطوم بحرى" ,BankCode: 11},
{ id: 88 ,  name:"السجانة" ,BankCode: 11},
{ id: 38 ,  name:"فرع القضارف" ,BankCode: 5},
{ id: 42 ,  name:"فرع الادارة العامة للشئون المالية" ,BankCode: 5},
{ id: 46 ,  name:"فرع السوق الشعبي" ,BankCode: 5},
{ id: 130 ,  name:"البلدية" ,BankCode: 13},
{ id: 133 ,  name:"كسلا" ,BankCode: 13},
{ id: 50 ,  name:"الخرطوم" ,BankCode: 7},
{ id: 277 ,  name:"الحصاحيصا" ,BankCode: 22},
{ id: 280 ,  name:"القضارف" ,BankCode: 22},
{ id: 283 ,  name:"بورتسودان" ,BankCode: 22},
{ id: 287 ,  name:"العمارات" ,BankCode: 22},
{ id: 139 ,  name:"سنكات" ,BankCode: 14},
{ id: 141 ,  name:"تنقاسى" ,BankCode: 14},
{ id: 142 ,  name:"الصناعات مدنى" ,BankCode: 14},
{ id: 146 ,  name:"ربك" ,BankCode: 14},
{ id: 149 ,  name:"السوق المحلى" ,BankCode: 14},
{ id: 152 ,  name:"الحصاحيصا" ,BankCode: 14},
{ id: 94 ,  name:"الرئاسة" ,BankCode: 11},
{ id: 95 ,  name:"سنار" ,BankCode: 11},
{ id: 96 ,  name:"الحصاحيصا" ,BankCode: 11},
{ id: 100 ,  name:"الجمهورية" ,BankCode: 11},
{ id: 103 ,  name:"الحصاحيصا" ,BankCode: 12},
{ id: 106 ,  name:"بورتسودان" ,BankCode: 12},
{ id: 109 ,  name:"توكيل الجامعة الاهلية" ,BankCode: 12},
{ id: 167 ,  name:"شندى" ,BankCode: 14},
{ id: 298 ,  name:"الفاشر" ,BankCode: 23},
{ id: 301 ,  name:"نيالا" ,BankCode: 23},
{ id: 169 ,  name:"القضارف" ,BankCode: 14},
{ id: 171 ,  name:"امدرمان" ,BankCode: 14},
{ id: 338 ,  name:"جامعة السودان" ,BankCode: 24},
{ id: 173 ,  name:"ام روابة" ,BankCode: 14},
{ id: 311 ,  name:"مدنى" ,BankCode: 23},
{ id: 175 ,  name:"كريمة" ,BankCode: 14},
{ id: 314 ,  name:"الرئاسة" ,BankCode: 23},
{ id: 177 ,  name:"السجانة" ,BankCode: 15},
{ id: 178 ,  name:"بحرى" ,BankCode: 15},
{ id: 321 ,  name:"هجليج" ,BankCode: 24},
{ id: 180 ,  name:"الفرع الرئيسى" ,BankCode: 15},
{ id: 326 ,  name:"نيالا" ,BankCode: 24},
{ id: 346 ,  name:"فرع الخرطوم" ,BankCode: 1},
{ id: 183 ,  name:"بورتسودان" ,BankCode: 16},
{ id: 184 ,  name:"القضارف" ,BankCode: 16},
{ id: 350 ,  name:"السوق العربى" ,BankCode: 4},
{ id: 186 ,  name:"كوستى" ,BankCode: 16},
{ id: 187 ,  name:"ربك" ,BankCode: 16},
{ id: 388 ,  name:"فرع كادقلى " ,BankCode: 6},
{ id: 189 ,  name:"الحاج عبدالله" ,BankCode: 16},
{ id: 356 ,  name:"الفرع الرئيسي" ,BankCode: 31},
{ id: 358 ,  name:"الرئاسة" ,BankCode: 35},
{ id: 360 ,  name:"فرع السجانة-الخرطوم" ,BankCode: 31},
{ id: 195 ,  name:"امدرمان" ,BankCode: 16},
{ id: 366 ,  name:"الرياض" ,BankCode: 11},
{ id: 392 ,  name:"فرع ياي" ,BankCode: 1},
{ id: 200 ,  name:"نيالا" ,BankCode: 16},
{ id: 371 ,  name:"فرع بورتسودان-الادخار" ,BankCode: 6},
{ id: 204 ,  name:"بحرى الصناعية" ,BankCode: 16},
{ id: 373 ,  name:"بنك السلام روتانا" ,BankCode: 29},
{ id: 206 ,  name:"الابيض" ,BankCode: 17},
{ id: 402 ,  name:"نيالا" ,BankCode: 1},
{ id: 405 ,  name:"بورتسودان" ,BankCode: 1},
{ id: 407 ,  name:"فرع سعد قشرة" ,BankCode: 2},
{ id: 212 ,  name:"كسلا" ,BankCode: 17},
{ id: 213 ,  name:"الفاشر" ,BankCode: 17},
{ id: 377 ,  name:"فرع سنار" ,BankCode: 1},
{ id: 215 ,  name:"السوق المحلى" ,BankCode: 17},
{ id: 420 ,  name:"مدنى" ,BankCode: 2},
{ id: 381 ,  name:"بنك الاسرة-الفرع الرئيسي" ,BankCode: 33},
{ id: 218 ,  name:"سنار" ,BankCode: 18},
{ id: 435 ,  name:"فرع المنطقة الصناعية بحري" ,BankCode: 2},
{ id: 440 ,  name:"نيالا" ,BankCode: 2},
{ id: 492 ,  name:"كوستي" ,BankCode: 3},
{ id: 495 ,  name:"الشواك" ,BankCode: 3},
{ id: 498 ,  name:"الابيض" ,BankCode: 3},
{ id: 499 ,  name:"غبيش" ,BankCode: 3},
{ id: 431 ,  name:"الشئون المالية" ,BankCode: 2},
{ id: 449 ,  name:"ابوجبيهة" ,BankCode: 3},
{ id: 450 ,  name:"الفولة" ,BankCode: 3},
{ id: 454 ,  name:"برام" ,BankCode: 3},
{ id: 457 ,  name:"فرع الكلاكلة" ,BankCode: 3},
{ id: 505 ,  name:"ابوزيد" ,BankCode: 3},
{ id: 460 ,  name:"رفاعة" ,BankCode: 3},
{ id: 461 ,  name:"الدمازين" ,BankCode: 3},
{ id: 463 ,  name:"فرع الجيلي" ,BankCode: 3},
{ id: 466 ,  name:"لتي" ,BankCode: 3},
{ id: 468 ,  name:"دنقلا" ,BankCode: 3},
{ id: 513 ,  name:"المناقل" ,BankCode: 3},
{ id: 470 ,  name:"ارقو" ,BankCode: 3},
{ id: 471 ,  name:"دلقو" ,BankCode: 3},
{ id: 516 ,  name:"كبكابية" ,BankCode: 3},
{ id: 520 ,  name:"ابوقمي" ,BankCode: 3},
{ id: 523 ,  name:"كادقلي" ,BankCode: 3},
{ id: 526 ,  name:"جوبا" ,BankCode: 3},
{ id: 475 ,  name:"عبري" ,BankCode: 3},
{ id: 564 ,  name:"الدمازين" ,BankCode: 4},
{ id: 529 ,  name:"الفاو" ,BankCode: 3},
{ id: 533 ,  name:"مدنى" ,BankCode: 3},
{ id: 536 ,  name:"راجا" ,BankCode: 4},
{ id: 480 ,  name:"الكاب" ,BankCode: 3},
{ id: 538 ,  name:"ملكال" ,BankCode: 4},
{ id: 539 ,  name:"السوق العربي " ,BankCode: 4},
{ id: 541 ,  name:"وادى حلفا" ,BankCode: 4},
{ id: 544 ,  name:"القولد" ,BankCode: 4},
{ id: 547 ,  name:"الدبة" ,BankCode: 4},
{ id: 569 ,  name:"كوستى" ,BankCode: 4},
{ id: 573 ,  name:"الحصاحيصا" ,BankCode: 4},
{ id: 577 ,  name:"فرع المنطقة الصناعية امدرمان" ,BankCode: 4},
{ id: 609 ,  name:"الرئاسة" ,BankCode: 16},
{ id: 613 ,  name:"الرئاسة" ,BankCode: 42},
{ id: 617 ,  name:"عفراء" ,BankCode: 8},
{ id: 581 ,  name:"عطبرة" ,BankCode: 4},
{ id: 585 ,  name:"فرع الباقير" ,BankCode: 4},
{ id: 589 ,  name:"فرع شارع النيل" ,BankCode: 4},
{ id: 619 ,  name:"الفولة" ,BankCode: 8},
{ id: 622 ,  name:"فرع الخرطوم جنوب" ,BankCode: 6},
{ id: 593 ,  name:"فرع السوق الشعبي - أمدرمان" ,BankCode: 31},
{ id: 596 ,  name:"فرع الرياض" ,BankCode: 2},
{ id: 599 ,  name:"فرع زالنجى " ,BankCode: 1},
{ id: 662 ,  name:"فرع بحري" ,BankCode: 32},
{ id: 665 ,  name:"الموردة" ,BankCode: 32},
{ id: 753 ,  name:" ابو حمامة " ,BankCode: 8},
{ id: 670 ,  name:"السجانه" ,BankCode: 34},
{ id: 755 ,  name:"السكة حديد بحري" ,BankCode: 2},
{ id: 758 ,  name:"شارع الوادي" ,BankCode: 24},
{ id: 762 ,  name:"ليبيا" ,BankCode: 3},
{ id: 766 ,  name:"الكلاكلة" ,BankCode: 24},
{ id: 677 ,  name:"القضارف" ,BankCode: 34},
{ id: 681 ,  name:"الميناء البري" ,BankCode: 34},
{ id: 685 ,  name:"مدني" ,BankCode: 35},
{ id: 767 ,  name:"بحري" ,BankCode: 24},
{ id: 630 ,  name:"نيالا" ,BankCode: 15},
{ id: 774 ,  name:"سوق ليبيا" ,BankCode: 8},
{ id: 634 ,  name:"نيالا" ,BankCode: 17},
{ id: 638 ,  name:"العمارات" ,BankCode: 17},
{ id: 642 ,  name:"الرئاسة" ,BankCode: 19},
{ id: 647 ,  name:"السجانة" ,BankCode: 21},
{ id: 650 ,  name:"جوبا" ,BankCode: 25},
{ id: 652 ,  name:"أويل" ,BankCode: 25},
{ id: 655 ,  name:"كسلا" ,BankCode: 31},
{ id: 657 ,  name:"سوق ليبيا" ,BankCode: 31},
{ id: 658 ,  name:"الأمم المتحدة" ,BankCode: 31},
{ id: 690 ,  name:"الفرع الرئيسي" ,BankCode: 42},
{ id: 694 ,  name:"أم درمان" ,BankCode: 42},
{ id: 698 ,  name:"فرع الثورة" ,BankCode: 2},
{ id: 702 ,  name:"المعمورة" ,BankCode: 11},
{ id: 706 ,  name:"المنطقة الحرة" ,BankCode: 14},
{ id: 710 ,  name:"سوق ليبيا" ,BankCode: 20},
{ id: 715 ,  name:"جامعة أفريقيا" ,BankCode: 20},
{ id: 719 ,  name:"سنجة" ,BankCode: 2},
{ id: 723 ,  name:"سوق ليبيا" ,BankCode: 28},
{ id: 727 ,  name:"فرع السوق المحلى   " ,BankCode: 6},
{ id: 731 ,  name:"فرع عطبرة" ,BankCode: 11},
{ id: 735 ,  name:"سنار" ,BankCode: 8},
{ id: 739 ,  name:"الكلاكلة" ,BankCode: 2},
{ id: 743 ,  name:"المغتربين" ,BankCode: 8},
{ id: 747 ,  name:"الرئاسة" ,BankCode: 46},
{ id: 223 ,  name:"السوق العربى" ,BankCode: 18},
{ id: 227 ,  name:"امدرمان" ,BankCode: 18},
{ id: 231 ,  name:"سوق امدرمان" ,BankCode: 19},
{ id: 235 ,  name:"توكيل المغتربين" ,BankCode: 19},
{ id: 239 ,  name:"بورتسودان" ,BankCode: 19},
{ id: 243 ,  name:"الحفير" ,BankCode: 20},
{ id: 247 ,  name:"بورتسودان" ,BankCode: 20},
{ id: 251 ,  name:"صرف المزاد" ,BankCode: 20},
{ id: 255 ,  name:"السوق المحلى" ,BankCode: 20},
{ id: 259 ,  name:"السوق العربى" ,BankCode: 20},
{ id: 264 ,  name:"بورتسودان" ,BankCode: 21},
{ id: 269 ,  name:"الفرع الرئيسى" ,BankCode: 21},
{ id: 273 ,  name:"الدمازين" ,BankCode: 22},
    ]),
    CommodityList: types.optional(types.frozen(), [{ id: "ALL", name: "ALL" }]),
    RealtedObjectList: types.optional(types.frozen(), []),
    SearchCommodityList: types.optional(types.frozen(), [{ label: "All", value: "1" }]),
  })
  .views(self => ({})) // eslint-disable-line @typescript-eslint/no-unused-vars
  .actions(self => ({
    GetCommodity: flow(function* GetCommodity(
      authorization: string,
    ) {
      self.IsCommodityLoading = true;
      try {
       // const data = yield api.GetCommodity(authorization);
       const data = yield api.GetJsonCommodity(authorization);
       
        if (data.kind === "ok") {

          parseString(data.Commodity , { trim: true }, function(_error, result) {
        

              self.CommodityList = data.Commodity;

           
            
          
          });
        } else {
          showAlert("common.noData");
        }
        self.IsCommodityLoading = false;
      } catch (erro) {}
    }),

    GetRelatedObject: flow(function* GetRelatedObject(
      authorization: string,
    ) {
      self.IsRelatedObjectLoading = true;
      try {
       // const data = yield api.GetCommodity(authorization);
       const data = yield api.GetJsonRelatedObject(authorization);
       console.log(data)
        if (data.kind === "ok") {

          parseString(data.RelatedObject , { trim: true }, function(_error, result) {
          
           
              self.RealtedObjectList = data.RelatedObject;

          });
        } else {
          showAlert("common.noData");
        }
        self.IsRelatedObjectLoading = false;
      } catch (erro) {}
    }),
    SearchCommodity: flow(function* SearchCommodity(
      authorization: string,searchword:string,
    ) {
      self.IsCommodityLoading = true;
      try {
        const data = yield api.SearchCommodity(authorization,searchword);
 
        if (data.kind === "ok") {

          parseString(data.SearchCommodity , { trim: true }, function(_error, result) {
          
            let returnData=result.ArrayOfCommodityDTO.CommodityDTO;
           
            if (returnData === "") {
              self.isEmptySearchCommodityList = true;
              self.SearchCommodityList = [];
            } else {
              self.isEmptySearchCommodityList = false;
              self.SearchCommodityList = returnData;
            }
            
          });
        } else {
          showAlert("common.noData");
        }
        self.IsCommodityLoading = false;
      } catch (erro) {}
    }),
    refreshCommodityList() {
      self.CommodityList = [];
    },
    refreshSearchCommodityList() {
      self.SearchCommodityList = [];
    },

  })) // eslint-disable-line @typescript-eslint/no-unused-vars

  /**
   * Un-comment the following to omit model attributes from your snapshots (and from async storage).
   * Useful for sensitive data like passwords, or transitive state like whether a modal is open.
   * Note that you'll need to import `omit` from ramda, which is already included in the project!
   */
  .postProcessSnapshot(
    omit([
      "signedSaved",
      "isButtonLoading",
      "hasError",
      "isEmptyList",
      "LookupList",
      "LookupDetail",
      "isLookupSaved",
      "fromHome",
    ]),
  );

type LookupStoreType = Instance<typeof LookupModel>;
export interface LookupStore extends LookupStoreType {}
type LookupStoreSnapshotType = SnapshotOut<typeof LookupModel>;
export interface LookupStoreSnapshot extends LookupStoreSnapshotType {}
