export const icons = {
  back: require("./arrow-left.png"),
  bullet: require("./bullet.png"),
  menuBar: require("./bars.png"),
  background: require("./background.jpg"),
  wall: require("./wall.jpg"),
  whiteWall: require("./white_wall.jpg"),
  loginLogo: require("./truck_logo_login.png"),
  cbosLogo: require("./CBOS_Logo.png"),
  imexLogo: require("./IMEX_Logo.png"),
  tradeLogo: require("./InternationalTrade_Logo.png"),
  redButton: require("./red_button.png"),
  blackButton: require("./black_button.jpg"),
  blackButton2: require("./black_button2.png"),
  redButton2: require("./red_button2.png"),
  addrequest: require("./icons8-add-96.png"),
  viewrequest: require("./icons8-search-more-96.png"),
  viewsmallrequest: require("./icons8-search-more-48.png"),
  phone: require("./phone.png"),
  blueButton: require("./blue_button.png"),
  downArrow: require("./downArrow.png"),
  callLogo: require("./call.png"),
  emailLogo: require("./email.png"),
  clientstatus: require("./risk.jpg"),
};

export type IconTypes = keyof typeof icons;
