import { GeneralApiProblem } from "./api-problem";

export interface User {
  id: number;
  name: string;
}

export type GetUsersResult = { kind: "ok"; users: User[] } | GeneralApiProblem;
export type GetUserResult = { kind: "ok"; user: User } | GeneralApiProblem;
export type GetClientStatus = { kind: "ok"; ClientStatus: any,status: number } | GeneralApiProblem;
export type LoginUserResult = { kind: "ok"; user: any; authorization: any,Status:any } | GeneralApiProblem;
export type ImFormResult = { kind: "ok"; ImForm: any } | GeneralApiProblem;
export type CommodityResult = { kind: "ok"; Commodity: any } | GeneralApiProblem;
export type RelatedObjectResult = { kind: "ok"; RelatedObject: any } | GeneralApiProblem;
export type SearchCommodityResult = { kind: "ok"; SearchCommodity: any } | GeneralApiProblem;
export type ExFormResult = { kind: "ok"; ExForm: any } | GeneralApiProblem;
export type ContractRequestResult = { kind: "ok"; ContractRequest: any } | GeneralApiProblem;
export type LicenseRequestResult = { kind: "ok"; LicenseRequest: any } | GeneralApiProblem;
export type OperationRequestResult = { kind: "ok"; OperationRequest: any } | GeneralApiProblem;
export type OperationTransferResult = { kind: "ok"; OperationTransfer: any } | GeneralApiProblem;
export type ClaimResult = { kind: "ok"; Claim: any;Status:any } | GeneralApiProblem;
export type MaturityResult = { kind: "ok"; Maturity: any } | GeneralApiProblem;
export type ClaimSettlementResult = { kind: "ok"; ClaimSettlement: any } | GeneralApiProblem;
export type PaymentResult = { kind: "ok"; Payment: any } | GeneralApiProblem;
export type MaturitySettlementResult = { kind: "ok"; MaturitySettlement: any } | GeneralApiProblem;
export type IssueResult = { kind: "ok"; Issue: any } | GeneralApiProblem;
export type ContractResult = { kind: "ok"; Contract: any } | GeneralApiProblem;
export type DocumentResult = { kind: "ok"; Document: any;Status: number } | GeneralApiProblem;
export type LicenseResult = { kind: "ok"; License: any } | GeneralApiProblem;
export type OperationResult = { kind: "ok"; Operation: any } | GeneralApiProblem;
export type HelpResult = { kind: "ok"; HelpList: any ;Status: number} | GeneralApiProblem;
export type GetUserInfo = { kind: "ok"; GetUser: any ;Status: number} | GeneralApiProblem;
export type VerifyUserResult = { kind: "ok"; VerifyUser: any } | GeneralApiProblem;
export type ChangePasswordResult = { kind: "ok"; ChangePassword: any } | GeneralApiProblem;
export type OTPChangePasswordResult = { kind: "ok"; OTPChangePassword: any } | GeneralApiProblem;
export type ImFormCommodityResult = { kind: "ok"; ImFormCommodityList: any } | GeneralApiProblem;
export type ExFormCommodityResult = { kind: "ok"; ExFormCommodityList: any } | GeneralApiProblem;
export type ContractRequestCommodityResult = { kind: "ok"; ContractRequestCommodityResultList: any } | GeneralApiProblem;
export type ContractRequestPaymentMethodResult = { kind: "ok"; ContractRequestPaymentMethodResultList: any } | GeneralApiProblem;
export type LicenseRequestCommodityResult = { kind: "ok"; LicenseRequestCommodityResultList: any } | GeneralApiProblem;
export type ContractCommodityResult = { kind: "ok"; ContractCommodityResultList: any } | GeneralApiProblem;
export type ContractPaymentMethodResult = { kind: "ok"; ContractPaymentMethodResultList: any } | GeneralApiProblem;
export type LicenseCommodityResult = { kind: "ok"; LicenseCommodityResultList: any } | GeneralApiProblem;
export type OperationRequestCommodityResult = { kind: "ok"; OperationRequestCommodityResultList: any } | GeneralApiProblem;
export type OperationRequestPaymentMethodResult = { kind: "ok"; OperationRequestPaymentMethodResultList: any } | GeneralApiProblem;
export type OperationCommodityResult = { kind: "ok"; OperationCommodityResultList: any } | GeneralApiProblem;
export type OperationPaymentMethodResult = { kind: "ok"; OperationPaymentMethodResultList: any } | GeneralApiProblem;
export type GetARateResult = { kind: "ok"; getaRate: any; Status: number } | GeneralApiProblem;
export type GetImListResult = { kind: "ok"; getImList: any; Status: number } | GeneralApiProblem;
export type GetExListResult = { kind: "ok"; getExList: any; Status: number } | GeneralApiProblem;
export type GetContractRequestListResult = { kind: "ok"; getContractRequestList: any; Status: number } | GeneralApiProblem;
export type GetLicenseRequestListResult = { kind: "ok"; getLicenseRequestList: any; Status: number } | GeneralApiProblem;
export type GetOperationRequestListResult = { kind: "ok"; getOperationRequestList: any; Status: number } | GeneralApiProblem;
export type GetOperationTransferListResult = { kind: "ok"; getOperationTransferList: any; Status: number } | GeneralApiProblem;
export type GetContractListResult = { kind: "ok"; getContractList: any; Status: number } | GeneralApiProblem;
export type GetLicenseListResult = { kind: "ok"; getLicenseList: any; Status: number } | GeneralApiProblem;
export type GetOperationListResult = { kind: "ok"; getOperationList: any; Status: number } | GeneralApiProblem;
export type GetClaimListResult = { kind: "ok"; getClaimList: any; Status: number } | GeneralApiProblem;
export type GetDocumentListResult = { kind: "ok"; getDocumentList: any; Status: number } | GeneralApiProblem;
export type GetClaimSettlementListResult = { kind: "ok"; getClaimSettlementList: any; Status: number } | GeneralApiProblem;
export type GetPaymentListResult = { kind: "ok"; getPaymentList: any; Status: number } | GeneralApiProblem;
export type GetMaturityListResult = { kind: "ok"; getMaturityList: any; Status: number } | GeneralApiProblem;
export type GetMaturitySettlementListResult = { kind: "ok"; getMaturitySettlementList: any; Status: number } | GeneralApiProblem;
export type GetIssueListResult = { kind: "ok"; IssueList: any; Status: number } | GeneralApiProblem;

