export type RootParamList = {
  primaryStack: undefined;
  authStack: undefined;
  verifyStack:undefined;
};

export type PrimaryParamList = {
  landing: undefined;
  UploadDocument:undefined;
  userSetting: undefined;
  qrScanner: undefined;
  ImFormList: undefined;
  ImFormDetail: undefined;
  ExFormList: undefined;
  ContractRequestList: undefined;
  ContractList: undefined;
  LicenseRequestList: undefined;
  LicenseList: undefined;
  OperationRequestList: undefined;
  OperationList: undefined;
  OperationTransferList: undefined;
  MaturityList: undefined;
  MaturitySettlementList: undefined;
  ClaimList: undefined;
  DocumentList: undefined;
  ClaimSettlementList: undefined;
  PaymentList: undefined;
  ExFormDetail: undefined;
  ContractRequestDetail: undefined;
  ContractDetail: undefined;
  LicenseRequestDetail: undefined;
  LicenseDetail: undefined;
  OperationRequestDetail: undefined;
  OperationDetail: undefined;
  OperationTransferDetail: undefined;
  MaturityDetail: undefined;
  MaturitySettlementDetail: undefined;
  ClaimDetail: undefined;
  ClaimSettlementDetail: undefined;
  DocumentDetail: undefined;
  PaymentDetail: undefined;
  SafetyCheck: undefined;
  SafetyCheckDetail: undefined;
  pdfViewer: undefined;
  ImFormSuccess: undefined;
  ImFormSpecial: undefined;
  signatureView: undefined;
  GetARateList: undefined;
  GetARate: undefined;
  Home: undefined;
  MyForm: undefined;
  ImForm: undefined;
  ExForm:undefined;
  MyRequests:undefined;
  MyExRequests:undefined;
  MyImRequests:undefined;
  ContractRequest:undefined;
  Contract:undefined;
  LicenseRequest:undefined;
  License:undefined;
  OperationRequest:undefined;
  Operation:undefined;
  OperationTransfer:undefined;
  Maturity:undefined;
  MaturitySettlement:undefined;
  NewContractRequest:undefined;
  NewContractRequestCommodity:undefined;
  NewContractRequestPaymentMethod:undefined;
  NewLicenseRequest:undefined;
  NewLicenseRequestCommodity:undefined;
  NewLicenseRequestPaymentMethod:undefined;
  UpdateContractRequest:undefined;
  UpdateContractRequestCommodity:undefined;
  UpdateContractRequestPaymentMethod:undefined;
  UpdateLicenseRequest:undefined;
  UpdateLicenseRequestCommodity:undefined;
  UpdateLicenseRequestPaymentMethod:undefined;
  NewOperationRequest:undefined;
  NewOperationRequestCommodity:undefined;
  NewOperationRequestPaymentMethod:undefined;
  UpdateOperationRequest:undefined;
  UpdateOperationRequestCommodity:undefined;
  UpdateOperationRequestPaymentMethod:undefined;
  Claim:undefined;
  ClaimSettlement:undefined;
  Document:undefined;
  Payment:undefined;
  ReportIssue:undefined;
  ClientStatus:undefined;
  ClientStatusBank:undefined;
  SearchClientStatus:undefined;
  Issue:undefined;
  IssueList:undefined;
  OTPScreen:undefined;
};
export type AuthParamList = {
  login: undefined;
  OTPScreen:undefined;
  HelpScreen: undefined;
  forgotpassword: undefined;
  Home:undefined;
  ChangePassword:undefined;
  OTPForgotPassword:undefined;
  OTPChangePassword:undefined;
};
